### ISSUE TITLE
Vehicle List

### ISSUE THREAD

**Issue by DanielCaspers** [DanielCaspers/CA-Portal#17]
**Motivation**
Customers should be able to see all vehicles which they have brought to Murphy Automotive, and perform actions related to them.

**Acceptance criteria**
- [x] 1. The user shall be able to see a list of their vehicles with the following information
- [x] 1.1. Year
- [x] 1.2 Make
- [x] 1.3 Model
- [x] 1.4. License
- [x] 1.5. LastServiceDate
- [x] 1.6. LastServiceMileage
- [x] 1.7. An indication of one or more recommended services, or an "all clear" checkmark #25 
- [x] 1.8 ~~If available, a thumbnail image of their car~~ Offloaded to #34 

- [x] 2. The user shall be able to perform or navigate to any of these actions on a single vehicle.
- [x] 2.1. View vehicle history (#23 )
- [x] 2.2. Schedule an appointment (#1)
- [x] 2.3. Get a list of available coupons (#19)
- [x] 2.4. View recommended service reminders (#25) 

- [x] 3. The default sort of the list is by
- [x] 3.1 recommended service severity, then by
- [x] 3.2 vehicle make, then by
- [x] 3.3 vehicle model

**Comment by DanielCaspers** [comment]
@scaspers please weigh in whether or not table sorting is a need. If so, I'd like more specifics on which columns, and their behaviors.

**Comment by DanielCaspers** [comment]
I'd also like to know if you have any data around the number of vehicles that most owners have in their account. I'm trying to figure out if this should be represented with a table, or if a list of rich cards would be better.

**Comment by YoMurphy** [comment]
I am assuming "2" above is after a vehicle is selected. Then I would suggest to add 2.4. Recommended Service reminders.

**Comment by DanielCaspers** [comment]
@YoMurphy , I caught your drift. I made a documentation mistake. Good catch :)

**Comment by DanielCaspers** [comment]
@YoMurphy I'd also be interested to hear your thoughts on if table sort is a need, and how different columns should be sortable if so. I'm asking because I think we should consider using something similar to the vehicle badge we developed in DI for quickly conveying year, make, model and color.

![image](https://user-images.githubusercontent.com/6056563/49262915-17c05400-f40e-11e8-9c18-3238321019d7.png)

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy I'd love your thoughts on my attached wireframes in the description, and if you feel we should start storing an image with the vehicle. We could always do without the image and use the colored name badge, but I think using a vehicle image will give a more premium feel.

**Comment by scaspers** [comment]
- Average number of vehicle per client is approx 2.5.  We do have clients with over 100 which are fleets and likely need file updating\cleansing.

- I am in favor of the vehicle image rather than the color badge.  I would then ask the question of who attaches the picture to the vehicle and how might we accomplish that?

- Maybe vehicle specific coupons\offers would not be visible until they look at Services Needed except for LOF coupons?

**Comment by DanielCaspers** [comment]
@scaspers not sure on your third point. What about tire coupons, or cabin air filter and wiper blades? You might not know they are due for those or if they'd get their oil change done with you if also doing tires?

**Comment by DanielCaspers** [comment]
New idea for image fallbacking. We would only show the severity when no img, and superimpose severity over the img when both are available. Could use more alignment work and slightly larger car image.

![image](https://user-images.githubusercontent.com/6056563/50046517-50953580-006a-11e9-938f-4385a0787a30.png)

**Comment by YoMurphy** [comment]
After further discussion I feel the Vehicle list should be the main page or dashboard. 
Possibly each vehicle is a widget itself. Example:
-Vehicle Picture icon followed by description. 
-4 icons shown- (Service Due or OK) - (Vehicle History) - (Schedule Service) - (Vehicle specific specials)
-Expanded text only if service is due.

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy this is blocked from completion until additional API support is available or requirements change.

For the short term, the most important to address are 
 1.5. LastServiceDate
 1.6. LastServiceMileage,

and if you'd like to have it
1.X NextServiceDate
1.Y NextServiceMileage

I currently think we should take "1.8 If available, a thumbnail image of their car" at a later point since this data isn't readily available yet. 

Here's the latest behavior of the feature:
![MyCar - Murphy Automotive (2)](https://user-images.githubusercontent.com/6056563/69907727-f20eb780-139f-11ea-870d-a3cfb989615d.gif) 

For fleets and those with lots of vehicles, max view on Desktop gives up to 3 columns.

![image](https://user-images.githubusercontent.com/6056563/69907723-dacfca00-139f-11ea-8bb1-4871745b79a9.png)

**Comment by YoMurphy** [comment]
@DanielCaspers, great work! 

- I would just say "Service needed", remove the s. Service can imply 1 or more, rather than Services would always imply more than 1.
- The changing icons in from of the "Service Needed" to match the concern may be confusing. Should we just stick to the exclamation point for Service needed. Green check for "No service needed".

**Comment by YoMurphy** [comment]
I would also favor the vehicle image background.

**Comment by DanielCaspers** [comment]
@YoMurphy, @scaspers and I decided no vehicle image for now until we build our own database of customer vehicle images. That we can always bring in later.

Great catch on the button text! Will change.

I am torn about the level of concern icon. Originally, I had it in the upper left of the card as an overall status of the card. I since moved it to the side of the button to communicate that the icon indicates the vehicle's aggregate level of concern. I am not a fan of thinning down to two icons as then it no longer communicates the same information. If it becomes binary and isn't understood, I would recommend then we put the number of recommended services before the button text. E.g. 2 services needed, 1 service needed. 

Given how torn all 3 of us have been about how to handle that, I recommend any further changes for expressing level of concern go through some form of usability testing with employees or close customers first to check our blind spots.

**Comment by scaspers** [comment]
1.5. LastServiceDate and  1.6. LastServiceMileage are now included in the clients and vehicles endpoints.
```
        "vehicleMaintDetails": [
            {
                "lofLastOdometer": -1,
                "lofLastDate": -63309600,
                "lofIntervalDays": null,
                "lofIntervalMiles": null
            }

```
negative or null values indicate that an oil change has not been done.

**Comment by DanielCaspers** [comment]
We decided I will add these on the client side. If non null or non-negative, client will add

 lofLastOdometer + lofIntervalMiles

 lofLastDate + lofIntervalDays

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy all originally agreed upon features here are provided and complete. 

We can file a separate issue for moving the recommended services icon if required.
